# Generated by Django 4.1.7 on 2023-03-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_edit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit',
        ),
    ]
